name: my_audiobook_app
description: A custom audiobook player

# Version wird automatisch hochgezählt bei Releases
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Audio Player
  just_audio: ^0.9.34
  # State Management
  flutter_bloc: ^8.1.3
  # Lokale Storage
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  shared_preferences: ^2.2.1
  # Utils
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
    - assets/audio/
