name: Audiobook Meme Reader
description: Isn meme reader for audiobooks

# Version wird automatisch hochgezählt bei Releases
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Audio
  just_audio: ^0.9.34
  # State Management
  flutter_bloc: ^8.1.3
  # Storage
  path_provider: ^2.1.15
  shared_preferences: ^2.1.1
  sqflite: ^2.2.8+4
  # Utils
  flutter_dotenv: ^5.1.0
  equatable: ^2.0.5
  logger: ^1.4.0
  # UI
  flutter_material_design_icons: ^1.1.7293

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  # Assets später hier einfügen
  # assets:
  #   - assets/audio/
  #   - assets/images/
